[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from    = "http://markokaportfolio.com/*"
  to      = "https://markokaportfolio.com/:splat"
  status  = 301
  force   = true

[[redirects]]
  from    = "http://www.markokaportfolio.com/*"
  to      = "https://markokaportfolio.com/:splat"
  status  = 301
  force   = true

[[redirects]]
  from    = "https://www.markokaportfolio.com/*"
  to      = "https://markokaportfolio.com/:splat"
  status  = 301
  force   = true

[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200
